# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedata',
            name='price',
        ),
        migrations.AddField(
            model_name='pricedata',
            name='price_high',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
