# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161003_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='price_high',
            field=models.CharField(max_length=100),
        ),
    ]
