# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161003_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='price_high',
            field=models.FloatField(),
        ),
    ]
