# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161004_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedata',
            name='price_high',
            field=models.CharField(max_length=100),
        ),
    ]
