# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161006_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
