# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pricedata_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricedata',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.Stock'),
        ),
    ]
