# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20161023_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundamentalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('end_date', models.CharField(blank=True, max_length=100)),
                ('amend', models.CharField(blank=True, max_length=100)),
                ('period_focus', models.CharField(blank=True, max_length=100)),
                ('fiscal_year', models.CharField(blank=True, max_length=100)),
                ('doc_type', models.CharField(blank=True, max_length=100)),
                ('revenues', models.CharField(blank=True, max_length=100)),
                ('op_income', models.CharField(blank=True, max_length=100)),
                ('net_income', models.CharField(blank=True, max_length=100)),
                ('eps_basic', models.CharField(blank=True, max_length=100)),
                ('eps_diluted', models.CharField(blank=True, max_length=100)),
                ('dividend', models.CharField(blank=True, max_length=100)),
                ('assets', models.CharField(blank=True, max_length=100)),
                ('cur_assets', models.CharField(blank=True, max_length=100)),
                ('cur_liab', models.CharField(blank=True, max_length=100)),
                ('cash', models.CharField(blank=True, max_length=100)),
                ('equity', models.CharField(blank=True, max_length=100)),
                ('cash_flow_op', models.CharField(blank=True, max_length=100)),
                ('cash_flow_inv', models.CharField(blank=True, max_length=100)),
                ('cash_flow_fin', models.CharField(blank=True, max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundamentals', to='api.Stock')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
