# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_fundamentaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default='', max_length=15000),
        ),
    ]
