# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_stock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
